### ISSUE TITLE
nc keeps connection open after EOF on debian

### ISSUE THREAD

**Issue by phoboslab** [hyperia-sk/memcache-info#1]
Not sure what exactly is causing this - maybe it's just a slightly different version of `nc` on Debian 9. The issue seems to be that `nc` is keeping the connection open after issuing the `stats` command. It never returns. Adding `-q 1` seems to fix the problem on my system.

I.e.:
```sh
slabStats=$(mktemp)
_echo "stats slabs" | nc -q 1 $HOST_NAME $PORT > $slabStats || (_echo "${red}Connect to $HOST_NAME:$PORT failed.${normal}" && exit 1)

stats=$(mktemp)
_echo "stats" | nc -q 1 $HOST_NAME $PORT > $stats
```

**Comment by arzzen** [comment]
Fixed, Thanks @phoboslab, for your contribution!
